language: node_js
node_js:
  - lts/*

services:
  - docker
  
before_install:
  - git config --global core.autocrlf false && git config --global core.filemode false
  - echo -e ${REPO_ACCESS_SSHKEY} > ~/.ssh/ci
  - chmod 400 ~/.ssh/ci
  - GIT_SSH_COMMAND="ssh -i ~/.ssh/ci -o StrictHostKeyChecking=no" git clone git@github.com:worstass/imgconv.git

script:
  - cd imgconv
#  - docker login --username=${ALIYUN_DOCKER_USER} --password=${ALIYUN_DOCKER_PASSWORD} registry.cn-hangzhou.aliyuncs.com
  - docker build --no-cache -t registry.cn-hangzhou.aliyuncs.com/imgconv/imgconv .
#  - docker push registry.cn-hangzhou.aliyuncs.com/91games/91games-allinone-ci
